print('Denniel Luis S. Sadian')
print('Cabugao, Gasan, Marinduque')
print('November 30, 2001')
print('Marinduque State College - School of Information and Computing Sciences')
print('Information Technology')
print('2nd Year BSIT-2F')
print('I like to watch movies.')
print('I like to stay up late at night.')
print('I like watching coding tutorials.')
print('I like to eat.')
print('I like to stay at home.')
